spring.application.name=backend
server.port=8081


# Your backend port (Spring Boot app that serves /api/...)
# Leave 8080 for the HAPI FHIR server and use 8081 here, for example
server.port=8081

# URL of your HAPI FHIR server (where JPA server runs)
fhir.server.base-url=http://localhost:8081/fhir

# Tell Spring Boot NOT to configure JDBC + JPA (no local DB in this app)
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
